global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "taskflow-api"
    static_configs:
      - targets: ["api:8080"]
    metrics_path: /metrics

  - job_name: "taskflow-worker"
    static_configs:
      - targets: ["worker:9091"]
    metrics_path: /metrics

  - job_name: "nats"
    static_configs:
      - targets: ["nats-exporter:7777"]
    metrics_path: /metrics


  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]
